export const APP = {
    SET_STATE: "SET_STATE",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

    GO_TO_ROUTE: "GO_TO_ROUTE",
    GO_TO_MAIN_ROUTE: "GO_TO_MAIN_ROUTE",
    BACK_ROUTE: "BACK_ROUTE",

    UPDATE_ROUTE_NAME: "UPDATE_ROUTE_NAME",
    
    LANG: {
        RUS: "RUS",
        ENG: "ENG"
    },

    NAV: {
        MISSINGS_PAGE: "MissingsPage",
        HOME_PAGE: "HomePage",
        LOGIN_PAGE: "LoginPage"
    }
}

export const PROFILE = {
    LOGIN: "PROFILE_LOGIN",
    LOGIN_SUCCESS: "PROFILE_LOGIN_SUCCESS",
    LOGIN_ERROR_INVALID: "PROFILE_LOGIN_ERROR_INVALID",
    LOGIN_ERROR: "PROFILE_LOGIN_ERROR",

    REGISTER: "PROFILE_REGISTER",
    REGISTER_SUCCESS: "PROFILE_REGISTER_SUCCESS",
    REGISTER_ERROR: "PROFILE_REGISTER_ERROR",

    LOGIN_ERRORS: {
        INVALID_PASSWORD: "INVALID_PASSWORD"
    }
}

export const MAP = {

}

export const MISSINGS = {
    FETCH_MISSINGS: "FETCH_MISSINGS",
    FETCH_MISSINGS_SUCCESS: "FETCH_MISSINGS_SUCCESS",
    FETCH_MISSINGS_ERROR: "FETCH_MISSINGS_ERROR"
}

export const API = {
    URL: "https://germangorodnev.com/petfinder/"
}